websocket:
  host: "0.0.0.0"
  port: 8765
  max_size: 2_000_000
  max_queue: 32
  read_limit: 2_000_000
  write_limit: 2_000_000
  update_interval: 1  # 更新间隔（秒）

redis:
  host: "localhost"
  port: 6379
  db: 0
  max_connections: 10
  encoding: "utf-8"
  decode_responses: True
  data_key: "real_time_data"

prometheus:
  port: 8000
